### PR TITLE
Turtle: Fix prefix containing "." or "-".

### PR DESCRIPTION
**Pull request by wismill**

### CODE REVIEW

**Comment by mjansing** [comment]
Thank again for this PR. I already published v0.3.1 of the package. Thanks for being patient.

**Comment by mjansing** [comment]
@wismill BTW: Your work is quiet good. Are you interested in becoming a collaborateur with push access for this repository?

**Comment by wismill** [comment]
@mjansing yes I would be glad to contribute to the next releases, although this tool works quiet well now.

**Comment by mjansing** [comment]
OK. granted you push access and you are now able to write to this repository. Feel free to create feature or bugfix branches directly in this repository which could be merged into master. I think working with pull request is a great think so I would prefer thise approach. 

I'll try to check changes quickly but I currently don't use Atom very often.

**Comment by mjansing** [comment]
@wismill FYI: I added your name to the [CHANGELOG.md](https://github.com/mjansing/language-rdf/blob/master/CHANGELOG.md). Are you on twitter? You can find me here: http://twitter.com/marcjansing.

**Pull request merged**
